"""
Reflection Result Schema for Research OS.

Defines structured output for the Reflection Agent.
Used for:
- Hallucination detection
- Confidence scoring
- Missing topic identification
- Citation verification
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, TypedDict


class ConfidenceLevel(Enum):
    """Confidence level classification."""

    HIGH = "high"  # Strong evidence, multiple sources
    MEDIUM = "medium"  # Moderate evidence, some sources
    LOW = "low"  # Weak evidence, few sources
    UNCERTAIN = "uncertain"  # Insufficient information


class ReasoningQuality(Enum):
    """Reasoning quality assessment."""

    EXCELLENT = "excellent"  # Clear logic, strong evidence
    GOOD = "good"  # Sound reasoning
    ADEQUATE = "adequate"  # Basic reasoning present
    WEAK = "weak"  # Gaps in reasoning
    FLAWED = "flawed"  # Logical errors detected


class HallucinationSeverity(Enum):
    """Hallucination severity levels."""

    NONE = "none"  # No hallucinations detected
    LOW = "low"  # Minor issues, mostly factual
    MEDIUM = "medium"  # Some unsupported claims
    HIGH = "high"  # Significant hallucinations
    CRITICAL = "critical"  # Extensive hallucinations


# TypedDict for LangGraph state compatibility
class ReflectionResultDict(TypedDict, total=False):
    """Dictionary-style reflection result for LangGraph compatibility."""

    requires_additional_research: bool
    missing_topics: List[str]
    hallucination_risk: float  # 0.0 to 1.0
    confidence_score: float  # 0.0 to 1.0
    reasoning_quality: float  # 0.0 to 1.0
    citation_issues: List[str]
    recommended_actions: List[str]
    new_tasks: List[Dict[str, Any]]
    quality_flags: List[str]
    confidence_level: str
    reasoning_assessment: str
    hallucination_severity: str


@dataclass
class CitationIssue:
    """Represents an issue with a citation."""

    citation: str
    issue_type: str  # missing | broken | hallucinated | unsupported
    severity: str  # high | medium | low
    description: str
    affected_claims: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "citation": self.citation,
            "issue_type": self.issue_type,
            "severity": self.severity,
            "description": self.description,
            "affected_claims": self.affected_claims,
        }


@dataclass
class MissingTopic:
    """Represents a missing topic in research."""

    topic: str
    priority: str  # high | medium | low
    suggested_queries: List[str] = field(default_factory=list)
    importance: float = 0.5

    def to_dict(self) -> Dict[str, Any]:
        return {
            "topic": self.topic,
            "priority": self.priority,
            "suggested_queries": self.suggested_queries,
            "importance": self.importance,
        }


@dataclass
class ResearchTask:
    """A new research task generated by reflection."""

    id: str
    description: str
    task_type: str  # web_search | github_analysis | pdf_analysis
    priority: int  # 1-10, higher is more important
    target_topics: List[str] = field(default_factory=list)
    suggested_sources: List[str] = field(default_factory=list)
    estimated_time_minutes: int = 5

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "description": self.description,
            "type": self.task_type,
            "priority": self.priority,
            "target_topics": self.target_topics,
            "suggested_sources": self.suggested_sources,
            "estimated_time_minutes": self.estimated_time_minutes,
        }


@dataclass
class ReflectionResult:
    """
    Structured reflection result for research validation.

    Provides detailed analysis of research quality including:
    - Hallucination detection
    - Confidence scoring
    - Missing topic identification
    - Citation verification
    - Reasoning quality assessment

    Attributes:
        requires_additional_research: Whether more research is needed
        missing_topics: Topics that need more coverage
        hallucination_risk: 0.0-1.0 risk score
        confidence_score: 0.0-1.0 confidence level
        reasoning_quality: 0.0-1.0 reasoning quality
        citation_issues: List of citation problems
        recommended_actions: Actions to improve the research
        new_tasks: Generated tasks for additional research
        quality_flags: Flags for quality issues
        confidence_level: Classification of confidence
        reasoning_assessment: Text assessment of reasoning
        hallucination_severity: Classification of hallucinations
        generated_at: Timestamp of generation
    """

    # Core findings
    requires_additional_research: bool = False
    missing_topics: List[str] = field(default_factory=list)

    # Quality scores (0.0 to 1.0)
    hallucination_risk: float = 0.0
    confidence_score: float = 0.0
    reasoning_quality: float = 0.0

    # Citation analysis
    citation_issues: List[str] = field(default_factory=list)

    # Recommendations
    recommended_actions: List[str] = field(default_factory=list)
    new_tasks: List[Dict[str, Any]] = field(default_factory=list)

    # Quality flags
    quality_flags: List[str] = field(default_factory=list)

    # Detailed classifications
    confidence_level: str = "medium"
    reasoning_assessment: str = ""
    hallucination_severity: str = "none"

    # Metadata
    generated_at: datetime = field(default_factory=datetime.utcnow)
    source_findings_count: int = 0
    source_citations_count: int = 0

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "requires_additional_research": self.requires_additional_research,
            "missing_topics": self.missing_topics,
            "hallucination_risk": self.hallucination_risk,
            "confidence_score": self.confidence_score,
            "reasoning_quality": self.reasoning_quality,
            "citation_issues": self.citation_issues,
            "recommended_actions": self.recommended_actions,
            "new_tasks": self.new_tasks,
            "quality_flags": self.quality_flags,
            "confidence_level": self.confidence_level,
            "reasoning_assessment": self.reasoning_assessment,
            "hallucination_severity": self.hallucination_severity,
            "generated_at": self.generated_at.isoformat(),
            "source_findings_count": self.source_findings_count,
            "source_citations_count": self.source_citations_count,
        }

    def to_langgraph_state(self) -> ReflectionResultDict:
        """Convert to LangGraph-compatible state dict."""
        return {
            "requires_additional_research": self.requires_additional_research,
            "missing_topics": self.missing_topics,
            "hallucination_risk": self.hallucination_risk,
            "confidence_score": self.confidence_score,
            "reasoning_quality": self.reasoning_quality,
            "citation_issues": self.citation_issues,
            "recommended_actions": self.recommended_actions,
            "new_tasks": self.new_tasks,
            "quality_flags": self.quality_flags,
            "confidence_level": self.confidence_level,
            "reasoning_assessment": self.reasoning_assessment,
            "hallucination_severity": self.hallucination_severity,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ReflectionResult":
        """Create from dictionary."""
        generated_at = data.get("generated_at")
        if isinstance(generated_at, str):
            generated_at = datetime.fromisoformat(generated_at)
        elif generated_at is None:
            generated_at = datetime.utcnow()

        return cls(
            requires_additional_research=data.get("requires_additional_research", False),
            missing_topics=data.get("missing_topics", []),
            hallucination_risk=data.get("hallucination_risk", 0.0),
            confidence_score=data.get("confidence_score", 0.0),
            reasoning_quality=data.get("reasoning_quality", 0.0),
            citation_issues=data.get("citation_issues", []),
            recommended_actions=data.get("recommended_actions", []),
            new_tasks=data.get("new_tasks", []),
            quality_flags=data.get("quality_flags", []),
            confidence_level=data.get("confidence_level", "medium"),
            reasoning_assessment=data.get("reasoning_assessment", ""),
            hallucination_severity=data.get("hallucination_severity", "none"),
            generated_at=generated_at,
            source_findings_count=data.get("source_findings_count", 0),
            source_citations_count=data.get("source_citations_count", 0),
        )

    @classmethod
    def from_reflection_output(
        cls,
        output_text: str,
        findings: List[Dict[str, Any]],
        sources: List[str],
    ) -> "ReflectionResult":
        """
        Parse reflection output from LLM into structured result.

        Args:
            output_text: Raw LLM output
            findings: Research findings
            sources: Source citations

        Returns:
            Structured ReflectionResult
        """
        result = cls()
        result.source_findings_count = len(findings)
        result.source_citations_count = len(sources)

        # Parse output for indicators
        output_lower = output_text.lower()

        # Check for additional research indicators
        if any(kw in output_lower for kw in ["more research", "need to", "insufficient", "gap"]):
            result.requires_additional_research = True

        # Check confidence indicators
        if any(
            kw in output_lower for kw in ["high confidence", "well-supported", "strong evidence"]
        ):
            result.confidence_score = 0.8
            result.confidence_level = "high"
        elif any(kw in output_lower for kw in ["low confidence", "uncertain", "weak"]):
            result.confidence_score = 0.3
            result.confidence_level = "low"
        else:
            result.confidence_score = 0.5
            result.confidence_level = "medium"

        # Check reasoning quality
        if any(kw in output_lower for kw in ["logical", "sound reasoning", "well-argued"]):
            result.reasoning_quality = 0.8
        elif any(kw in output_lower for kw in ["flawed", "illogical", "gaps"]):
            result.reasoning_quality = 0.4
        else:
            result.reasoning_quality = 0.6

        # Extract missing topics (simplified parsing)
        result.quality_flags.append(output_text[:500])

        return result

    def add_missing_topic(self, topic: str, priority: str = "medium") -> None:
        """Add a missing topic to the result."""
        if topic not in self.missing_topics:
            self.missing_topics.append(topic)

    def add_citation_issue(self, issue: str) -> None:
        """Add a citation issue."""
        if issue not in self.citation_issues:
            self.citation_issues.append(issue)

    def add_recommended_action(self, action: str) -> None:
        """Add a recommended action."""
        if action not in self.recommended_actions:
            self.recommended_actions.append(action)

    def add_quality_flag(self, flag: str) -> None:
        """Add a quality flag."""
        if flag not in self.quality_flags:
            self.quality_flags.append(flag)

    def add_new_task(self, task: Dict[str, Any]) -> None:
        """Add a new research task."""
        self.new_tasks.append(task)

    @property
    def is_high_quality(self) -> bool:
        """Check if research meets quality threshold."""
        return (
            self.confidence_score >= 0.7
            and self.reasoning_quality >= 0.6
            and self.hallucination_risk < 0.3
            and not self.citation_issues
        )

    @property
    def needs_immediate_revision(self) -> bool:
        """Check if immediate revision is required."""
        return (
            self.hallucination_risk >= 0.5
            or self.confidence_score < 0.3
            or len(self.citation_issues) >= 3
        )

    def __str__(self) -> str:
        """String representation."""
        return (
            f"ReflectionResult("
            f"confidence={self.confidence_score:.2f}, "
            f"hallucination_risk={self.hallucination_risk:.2f}, "
            f"reasoning={self.reasoning_quality:.2f}, "
            f"missing_topics={len(self.missing_topics)}, "
            f"citation_issues={len(self.citation_issues)})"
        )
